name: Mintlify Continuous Integration
run-name: run eslint against mdx and md files

on:
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: corepack enable
      - run: pnpm i
      - run: pnpm lint    
